services:

stages:
  - build

variables:

build:
  stage: build
  only:
    - ci-cd
  script:
    - docker info
    - docker build -t bol-explorer .
    - docker stop bol-explorer || true
    - docker rm bol-explorer || true
    - docker run -d --name bol-explorer -e "VIRTUAL_HOST=explorer.bolchain.net" -e "LETSENCRYPT_HOST=explorer.bolchain.net" -e "LETSENCRYPT_EMAIL=admin@bolchain.net" bol-explorer 
  tags:
    - internal

