FROM nginx:1.25.1 AS base
WORKDIR /app
EXPOSE 80

FROM node:16.17.0 AS build
WORKDIR /repo

COPY ./package.json ./
COPY ./package-lock.json ./

RUN npm install

COPY . .
COPY ./.env_testnet ./.env

RUN npm run compile-sass
RUN npm run minify-sass
RUN npm run build



FROM build AS publish
RUN cp -a build/. /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app /usr/share/nginx/html
COPY ./nginx.conf /etc/nginx/nginx.conf
COPY ./robots.txt /etc/nginx/robots.txt

