apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: __CI_BUILD_REF_SLUG__-explorer
  namespace: __CI_BUILD_REF_SLUG__
  labels:
    app: __CI_BUILD_REF_SLUG__-explorer
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: letsencrypt-staging
spec:
  tls:
  - hosts:
    - explorer.__CI_ENV_SLUG__.bolchain.net
    secretName: __CI_BUILD_REF_SLUG__-explorer-tls-staging
  rules:
  - host: explorer.__CI_ENV_SLUG__.bolchain.net
    http:
      paths:
      - path: /
        backend:
          serviceName: __CI_BUILD_REF_SLUG__-explorer
          servicePort: 80